### ISSUE TITLE
authentication / credentials for live-server introspection query

### ISSUE THREAD

**Issue by MartinLorensen** [Macroz/GraphQLviz#1]
There does not seem to be any way to get credentials or use "standard" NTLM authentication when doint a live-server introspection query. An exception is thrown which contains the returned result, being a 401 status and a  "WWW-Authenticate" ["Negotiate" "NTLM"]-header.

The simple workaround is be to manually do the introspection query and store the result to a file, and then feed the file into GraphQLviz.

**Comment by Macroz** [comment]
Hi,

Proxy-ing or saving the result to a file is a good workaround. However something else maybe also easy to support. I'll look into this. We don't have any authentication for this in our backend. Which one are you using?

-Markku

**Comment by MartinLorensen** [comment]
Our GraphQL-dotnet server is running inside IIS, which handles the NTLM authentication.

When our normal client connects fra JavaScript, it just includes an option the the network layer of react:

`````` javascript
_reactRelay2.default.injectNetworkLayer(new _reactRelay2.default.DefaultNetworkLayer("some-url/graphql", {
      credentials: "include" }));```

However, the webbrowser is authenticated and this might be very different from a command-prompt - and work cross-platform. My use of lisp ended some 20 years ago...
``````

**Comment by MartinLorensen** [comment]
I noted that the [http-library](https://github.com/dakrone/clj-http#authentication) you are using does not seem to support NTLM. However, just supporting some or all of the auth-mechanisms would be fine - I can enable either Basic or Digest Auth on the IIS.

**Comment by Macroz** [comment]
I released v0.4.0 (you can find the binary in the releases). It contains support for all the authentication methods `clj-http` supports (i.e. basic, digest and oauth2). Can you have a try and see if it works?

**Comment by MartinLorensen** [comment]
I have tried to test this but with little success. I do however still assume that it is my own incompetence that is to blame! ;-) I would like to givet it another go some day in the future, possibly with wireshark or the like to assist me in understanding what is going on.

A password-prompt would have been nice though - having passwords on screen and in the shell-history is bad practice I guess. There is an issue with escaping special chars in the password "the right way" in the shell (powershell in my case), which may be part of the reason I can't get it working.

**Comment by Macroz** [comment]
Let me know if it doesn't work.

I can add a password prompt if the password is not given. Another common case is to read it from an environment variable.

**Comment by Macroz** [comment]
I added `--password-prompt` to read passwords from the console. This is in release `0.5.0`. I'm closing this issue now. Thanks for the ideas!
