### ISSUE TITLE
Introspection query returns outer "data" element

### ISSUE THREAD

**Issue by MartinLorensen** [Macroz/GraphQLviz#2]
Hi,

It seems the introspection query returns a "data" element contaning the "__schema", where as the load-schema function expect the __schema to be the outer most key.

The workaround is to just strip the "data" dictionary by hand (or a simple script).

`{
  "data": {
    "__schema": {
    ...
    }
  }
}`

**Comment by Macroz** [comment]
Hi!

I have one other report of this behavior. What backend are you using? We are using OpenTripPlanner in our project, where we implemented this ourselves using graphl-java , so maybe it's not exactly same with everything else. I'll look into it.

-Markku

**Comment by MartinLorensen** [comment]
We are using a fork of [GraphQL-dotnet](https://github.com/hudl/graphql-dotnet). And since the build-in introspection query doesn't support authentication, I am using a self-brewed command-line tool to actually dump the query output. However, it does look the same when using GraphiQL using your resource-intrespection-query.

Looking at [graphql.org](http://graphql.org/docs/queries/), it does look like any query (which introspection query is just a special case of) would return a dictionary with a single "data" key.

**Comment by Macroz** [comment]
After a quick look I dump the result after stripping away the "data" key. So maybe I should dump with the data key and strip it after loading from the file.

**Comment by Macroz** [comment]
Ok, I changed so that the file contains now the "data" key as well. Should make it easier to provide your own file. This is in version 0.3.0.

**Comment by Macroz** [comment]
You can also check this with the 0.4.0 that I just released.

**Comment by MartinLorensen** [comment]
Forgot to say this solved our problem! Thanks!
