### ISSUE TITLE
XxxConnection / XxxEdges

### ISSUE THREAD

**Issue by MartinLorensen** [Macroz/GraphQLviz#3]
While [GraphQL does not specify any standard for doing paging/collections](https://github.com/facebook/graphql/issues/4#issuecomment-118162627), it seems that a convention is to have a XxxConnection-type and possilby a XxxEdge-type, which always contains a specific sets of fields and reference an instance of Xxx.

With larger graphs with many collections with paging, the Connect/Edge-types clutter the graph quite a bit. It would be nice to have a way of replacing any of these paging classes with a "one to many" connection in the dot-graph. This could be indicated with a star either at the arrow or prefixed/suffixed the connection name.

As there is no specification, this might be a bit tricky to get right, matching might have to be a bit flexible - and this might be a feature that is not on by default.
- [Facebooks convension](https://github.com/facebook/graphql/issues/4#issuecomment-118162627) seems to be XxxConnection and XxxConnectionEdge.
- graphql-dotnet seems Edge-types has no incoming edges, only an outgoing connection to the underlying type. From the example dataset I can see the Connection-type also has a connection to the Edge-type (which sounds reasonable).

**Comment by Macroz** [comment]
Do you have a suitable example file? I have not so far had a need to filter out edges, but I can see how that would be useful. Thanks.

**Comment by MartinLorensen** [comment]
I just found that the specification - it is not in GraphQL, but rather a relay-thing found [here](https://facebook.github.io/relay/graphql/connections.htm).

A rather "simplified" version of our current model is [attached](https://github.com/Macroz/GraphQLviz/files/140789/bar.json.txt) (might not be 100% valid GraphQL-metadata, but the tool passes it and produces a graph illustrating the "problem").

**Comment by Macroz** [comment]
Ok, how about [graphqlviz-0.5.0-preview.zip](https://github.com/Macroz/GraphQLviz/files/142720/graphqlviz-0.5.0-preview.zip)? Does it work for you?

**Comment by arunlals** [comment]
fdgdfgfd
df
gdf

**Comment by MartinLorensen** [comment]
That works perfectly. Thanks a lot!

BTW: Sorry for the delay. Some how i missed the original notification of your post - so it wasn't until I received the comment from "arunappulal" i noted the response.
