### ISSUE TITLE
Maybe better installation instructions...

### ISSUE THREAD

**Issue by orefalo** [Macroz/GraphQLviz#4]
For the newbie,
For the neo fit not use to these technologies,
For the lazy, a ready to use package to run

Thank you

**Comment by Macroz** [comment]
Ideally this would not be a JVM project. It'd be nice to have GraphQLviz run in the browser or as node package.

In the meantime, I'll see what I can do.

**Comment by Macroz** [comment]
I have improved the instructions a bit. I'm closing this issue for now. If you have more specific questions, please let me know and I'll try to help you.
